<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * Find posts by trip ID
     * @param $tripId
     * @return Post[]
     */
    public function findByTripId($tripId)
    {
        return $this->createQueryBuilder('p')
            ->where('p.tripId = :trip_id')
            ->setParameter('trip_id', $tripId)
            ->getQuery()
            ->getResult();
    }
}
