<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * Find posts by user ID
     * @param $userId
     * @return array
     */
    public function findByUserId($userId)
    {
        return $this->createQueryBuilder('p')
            ->orWhere('p.users = :only')
            ->orWhere('p.users LIKE :first')
            ->orWhere('p.users LIKE :middle')
            ->orWhere('p.users LIKE :last')
            ->setParameters([
                'only' => $userId,
                'first' => $userId . ',%',
                'middle' => '%,' . $userId . ',%',
                'last' => '%,' . $userId,
            ])
            ->getQuery()
            ->getResult();
    }

    /**
     * Find posts by trip ID
     * @param $tripId
     * @return array
     */
    public function findByTripId($tripId)
    {
        return $this->createQueryBuilder('p')
            ->where('p.tripId = :trip_id')
            ->setParameter('trip_id', $tripId)
            ->getQuery()
            ->getResult();
    }
}
