parameters:
#    parameter_name: value

services:
    api_view_listener:
        class: Api\EventListener\ApiViewListener
        arguments:
            - "@jms_serializer"
        tags:
            - { name: kernel.event_subscriber }
